---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
  with_items:
    - "nova-compute"
    - "nova-libvirt/secrets"
  when: inventory_hostname in groups['compute']

- name: Copy over ceph files
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/nova-compute/"
  with_fileglob:
    - "{{ node_custom_config }}/nova/ceph*"
  when: inventory_hostname in groups['compute']

- name: Copy over ceph files
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/nova-libvirt/"
  with_fileglob:
    - "{{ node_custom_config }}/nova/ceph*"
  when: inventory_hostname in groups['compute']


- name: Pushing secrets xml for libvirt
  template:
    src: "secret.xml.j2"
    dest: "{{ node_config_directory }}/nova-libvirt/secrets/{{ rbd_secret_uuid }}.xml"
    mode: "0600"
  when: inventory_hostname in groups['compute']

- name: Extract key from file
  local_action: shell cat {{ node_custom_config }}/nova/ceph.client.kolla-cinder.keyring | grep -E 'key\s*=' | awk '{ print $3 }'
  register: cephx_raw_key

- name: Pushing secrets key for libvirt
  copy:
    content: "{{ cephx_raw_key.stdout }}"
    dest: "{{ node_config_directory }}/nova-libvirt/secrets/{{ rbd_secret_uuid }}.base64"
    mode: "0600"
  when: inventory_hostname in groups['compute']
