---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/cinder-{{ item }}"
    state: "directory"
  when: inventory_hostname in groups['cinder-volume'] or
        inventory_hostname in groups['cinder-backup']
  with_items:
    - volume
    - backup

- name: Copy over Ceph files for cinder-volume
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/cinder-volume/"
  with_fileglob:
    - "{{ node_custom_config }}/cinder/ceph*"

- name: Copy over Ceph files for cinder-backup
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/cinder-backup/"
  with_fileglob:
    - "{{ node_custom_config }}/cinder/ceph*"
